apiVersion: gopron.online/v1
kind: DeployStack
metadata:
  labels:
    app.kubernetes.io/name: deploystack
    app.kubernetes.io/instance: deploystack-sample
    app.kubernetes.io/part-of: deploy-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: deploy-operator
  name: deploystack
spec:
# 服务列表(前缀+"-"+服务名称:版本)
  appsList:
    hello: latest
    wxweb: latest

  appsConf:
    web:
      wxweb:
      - replicasForWeb
    app:
      hello:
      - replicasForHello
      - resourcesMemoryForHello
  hello:
  - replicasForHello
  - resourcesMemoryForHello
  #以下按服务类定义配置:web、go、node、java等
  #前端类
  web:
  - replicasForWeb
  #后端类
  app:
  - portForGrpc
  - replicasForDefault
  #..其他类
   #默认通用配置项
  default:
  - replicasForDefault
  - resourcesMemoryForDefault
  - resourcesCpuForDefault
  - imageRegistryForDefault
  - imageSecretsForDefault
  - imageNamespaceForDefault
  - volumeCmForDefault



#路由: Prefix、Exact、ImplementationSpecific
  ingress:
  - host: hello.gopron.online
    name: hello
    https: true
    match:
      /hello/*: hello
      /test/*: test
    annotations:
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  - host: gw.gopron.online
    name: hello
    match:
      /hello22/*: hello
      /test2/*: test
  - host: test.gopron.online
    name: test
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    prefix:
      /*: test 8081
      /hello: hello
  #env
  #configmap:global-config
  configMapName: global-config
  configs:
  #secret:global-secret
  secret:
  #resources
  resourcesMemoryForDefault: 10Mi-100Mi
  resourcesCpuForDefault: 10m-100m
  resourcesMemoryForHello: 512Mi-2048Mi
  #port
  portForGrpc: 5011
  portForHttp: 8080
  #volume
  volumeCmForDefault: /www/config
  volumeCmForData: /www/config
  #probe
  probeReadyForHttp: true
  probeReadyTcpPort: 8800
  probeReadyHttpPort: 6060
  #images
  imageRegistryForDefault: registry.cn-hangzhou.aliyuncs.com/unipal
  imageSecretsForDefault: regcred-vpc
  imageNamespaceForDefault: prod

  #replicas
  replicasForDefault: 1
  replicasForHello: 0
  #namespace
  namespaceForDefault: prod
  namespace: prod
