apiVersion: gopron.online/v1
kind: DeployStack
metadata:
  labels:
    app.kubernetes.io/name: deploystack
    app.kubernetes.io/instance: deploystack-sample
    app.kubernetes.io/part-of: deploy-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: deploy-operator
  name: deploystack
spec:
#全局配置项：default; 分类配置项:web、app、node; 服务配置:appsConf:
#appsConf:default+类别+自定义
#default配置项:xxForDefault命名; 自定义服务配置项: xxForName命名,
#对应k8s列表配置项：name=key, value=value

# 所有服务列表(前缀+"-"+服务名称:版本),支持上下线。
#当不在appsConf中配置时,使用default配置
  appsList:
    hello: latest
#服务配置，支持覆盖，[keyForName:value]
#appsConf: 服务配置
#  type: 服务类别
#  - item: 自定义配置项
  appsConf:
    web:
      appweb: []
      wxweb:
      - probeReadyTcpForDefault:8800
      - probeHttpEnable:false
    app:
      hello:
      - replicasForDefault:3
    sts:
      broker: []

  #以下按服务类定义配置:web、go、node、java等
  #服务类别,和appsConf中的类别一致
  web:
  - portForHttp
  - replicasForWeb
  #后端类
  app:
  - portForGrpc
  sts:
  - portForGrpc
  #..其他类
   #默认通用配置项
   #portFor 定义端口,格式:portFor+自定义名字
   #resource 资源限制
   #image 定义镜像
   #volume定义挂载卷配置:支持格式：volume+挂载类型+For+自定义名字,如volumeCmForConf：定义服务配置文件
   #volumeLocalFor 本地目录
   #volumeCmFor 定义配置文件
   #volumeSecretFor 定义加密配置
   #其他：volumePvcFor、volumeNfsFor、volumeGfsFor
   #porbeReady:定义健康检查
  default:
  - resourcesMemoryForDefault
  - resourcesCpuForDefault
  - imageRegistryForDefault
  - imageSecretsForDefault
  - imageNamespaceForDefault
  - namespaceForDefault
  - volumeCmForDefault
  - probeReadyTcpForDefault

#

#路由: Prefix、Exact、ImplementationSpecific
  ingress:
  - host: hello.gopron.online
    name: hello
    https: true
    match:
      /hello/*: hello
      /test/*: test
    annotations:
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  - host: gw.gopron.online
    name: hello
    match:
      /hello22/*: hello
      /test2/*: test
  - host: test.gopron.online
    name: test
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    prefix:
      /*: test 8081
      /hello: hello
  #env
  #configmap:global-config
  configs:
  #secret:global-secret
  secret:
  #resources
  resourcesMemoryForDefault: 10Mi-100Mi
  resourcesCpuForDefault: 10m-100m

  #port
  portForGrpc: 5010
  portForHttp: 8080
  #volume
  volumeCmForDefault: /www/config/
  volumeSecretForCerts: /etc/certs

  #probe
  probeHttpEnable: true
  probeReadyTcpForWeb: 8800
  probeReadyTcpForDefault: 6060

  #images
  imageRegistryForDefault: registry.cn-hangzhou.aliyuncs.com/unipal
  imageSecretsForDefault: regcred-vpc
  imageNamespaceForDefault: stage

  #replicas
  replicasForDefault: 1
  replicasForWeb: 1
 
  #namespace
  namespaceForDefault: prod
