apiVersion: gopron.online/v1
kind: DeployStack
metadata:
  labels:
    app.kubernetes.io/name: deploystack
    app.kubernetes.io/instance: deploystack-sample
    app.kubernetes.io/part-of: deploy-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: deploy-operator
  name: deploystack
spec:
  apps:
    test:
      replicas: 0
      imageRegistry: github.com
      registrySecrets: regcred-vpc
      ports:
      - name: grpc
        port: 5010 
  appsList:
    hello: latest
    test: latest
  replicas: 0
  imageRegistry: nginx
  imagePullPolicy: Always
  registrySecrets: regcred-vpc
  namespace: default
  configs:
    CONFIG_SERVER_URL: http://nacos.gopron.online
    PROFILES_ACTIVE: DEV
    CONFIG_SERVER_USER: nacos
    CONFIG_SERVER_PWDS: nacos
  secret:
    CONFIG_DB_USERNAME: cm9vdAo=
    CONFIG_DB_PASSWORD: MTIzNDU2Cg==
  service:
    type: ClusterIP
  ports:
  - name: grpc
    port: 5010
  - name: http
    port: 8800
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 512Mi
#路由: Prefix、Exact、ImplementationSpecific
  ingress:
  - host: hello.gopron.online
    name: hello
    https: true
    match:
      /hello/*: hello
      /test/*: test
    annotations:
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  - host: gw.gopron.online
    name: hello
    match:
      /hello22/*: hello
      /test2/*: test
  - host: test.gopron.online
    name: test
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/server-snippet: |
        set $agentflag 0;
        if ($http_user_agent ~* "(python-requests|Apache-HttpClient|python)" ){
          set $agentflag 1;
        }
        if ($request_uri ~* "(^/gaocc|diagnosis|/internet)" ){
          set $agentflag 1;
        }
        if ( $agentflag = 1 ) {
          return 444;
        }
    prefix:
      /*: test 8081
      /hello: hello


  portForGrpc: 5010
  portForHttp: 8080
