# permissions for end users to view mykinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mykind-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: 02-kubebuilder
    app.kubernetes.io/part-of: 02-kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: mykind-viewer-role
rules:
- apiGroups:
  - apps.gopron.online
  resources:
  - mykinds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.gopron.online
  resources:
  - mykinds/status
  verbs:
  - get
